Cora:
  alpha: 0.1
  lambda: 0.5
  num_layers: 64
  dim_hidden: 64
Pubmed:
  alpha: 0.1
  lambda: 0.4
  num_layers: 16
  dim_hidden: 256
Citeseer:
  alpha: 0.1
  lambda: 0.6
  num_layers: 32
  dim_hidden: 256
